// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "6805cb63a80d8bdfd5ad74002bffea57"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"3609d6d8e25a31cceeaf13ab842c5c33": "1f8b08000000000000ffb25174f1770e890c7055c828c9cdb1e3b201510a398979e9b64aa9794a2081d4c4143b2e050505059bdcd4924485e48cc4a2e2d4125ba5d010375d0b25a8544966494eaa5d0888b4d18770b86cf4217a6d92f2532a21ea2e4cbcd87bb1e162ef858d1776805817765decbdb0fbc28e0b3b2e36285c6cbcb0e1c2ce8b4d5c36fa101d36fa604701020000ffffdfaf3040a4000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("myBox", "./assets")
		b.SetResolver("index.html", packr.Pointer{ForwardBox: gk, ForwardPath: "3609d6d8e25a31cceeaf13ab842c5c33"})
	}()
	return nil
}()
